# Generated by Django 5.1 on 2024-12-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='content',
            new_name='Content',
        ),
    ]
